"use client";

import CommentListing from "@/components/CommentListing";
import React, { FC } from "react";
import ButtonSecondary from "@/shared/ButtonSecondary";
import Image from "next/image";
import gemini_logo from "@/images/Google_Gemini.svg";

export interface ChatPageProps {}

const ChatPage: FC<ChatPageProps> = ({}) => {
  const renderSection1 = () => {
    return (
      <div className="listingSection__wrap w-full flex flex-col items-center text-center sm:rounded-2xl sm:border border-neutral-200 dark:border-neutral-700 space-y-6 sm:space-y-7 px-0 sm:p-6 xl:p-8">
        <Image src={gemini_logo} alt="Gemini" height={50} />

        {/* ---- */}
        <p className="text-neutral-500 dark:text-neutral-400">
          The content is generated by Gemini AI. The content is generated based
          on the user's preferences and interests.
        </p>
      </div>
    );
  };

  const renderSection2 = () => {
    return (
      <div className="listingSection__wrap">
        {/* HEADING */}
        <h2 className="text-2xl font-semibold">Reviews (23 reviews)</h2>
        <div className="w-14 border-b border-neutral-200 dark:border-neutral-700"></div>

        {/* comment */}
        <div className="divide-y divide-neutral-100 dark:divide-neutral-800">
          <CommentListing hasListingTitle className="pb-8" />
          <CommentListing hasListingTitle className="py-8" />
          <CommentListing hasListingTitle className="py-8" />
          <CommentListing hasListingTitle className="py-8" />
          <div className="pt-8">
            <ButtonSecondary>View more 20 reviews</ButtonSecondary>
          </div>
        </div>
      </div>
    );
  };

  return (
    <div className={`nc-ChatPage `}>
      <main className="container mt-12 mb-24 lg:mb-32 flex flex-col lg:flex-row">
        <div className="w-full space-y-8 lg:space-y-10 flex-shrink-0">
          {renderSection1()}
          {renderSection2()}
        </div>
      </main>
    </div>
  );
};

export default ChatPage;
